#!/bin/bash
#
# This is a race condition, but on linux 2.4 there isn't
# any easy way to find out which input device(s) associate
# with the USB device that was just added. We just make
# a few big assumptions and set up an inputpipe for the
# highest numbered event device. Yep, this is really gross.
#

HOST=wasabi

if [ "$ACTION" = add ] && [ -f "$DEVICE" ]; then
EVDEV=`ls /dev/input/event* | sort -n | tail -n 1`
/usr/local/bin/inputpipe-client $HOST $EVDEV&
fi
